^ Welcome to Pegex!

Pegex is a "Acmeist"<http://acmeism.org> parser framework. It combines a "PEG"<http://en.wikipedia.org/wiki/Parsing_expression_grammar> parser grammar syntax, with PCRE compatible "Regular Expressions"<http://en.wikipedia.org/wiki/Regular_expression> as the match tokens. Pegex draws heavily from "Perl 6 Rules"<http://perlcabal.org/syn/S05.html>, and works equivalently in many modern programming languages.

With Pegex you can easily define new mini languages that can be equally compiled in many programming languages.

----

A specification will be forthcoming, but check out these URLs that show Pegex in action:

* http://github.com/ingydotnet/pegex-pm - The Perl 5 Pegex implementation.
* http://github.com/ingydotnet/testml-pgx - The Pegex grammar for "TestML"<http://testml.org> implementations.
* http://github.com/ingydotnet/testml-pm  - The Perl 5 TestML implementation. Look at `lib/TestML/Parser/Grammar.pm`.
* http://github.com/ingydotnet/testml-pm6  - The Perl 6 TestML implementation. Compare the Perl 6 grammar to Pegex!
* "The TestML Specification"<http://www.testml.org/specification/language/> - An annotated Pegex grammar.

`--` "Ingy döt Net"<http://ingy.net>
